#!/usr/bin/env python3
"""
FORD MODEL — MASTER SCRIPTBOOK
FIRST-PRINCIPLES INTEGRATED VERSION
===================================
Author: Al Ford (theory), computational implementation
Version: 2026-05-14 — first-principles restoration pass

What this version fixes
-----------------------
The previous integration preserved many outputs but compressed too much of the
"why" into assignments. This version restores the first-principles spine.

The script now explicitly separates:

  A. Primitive principles
  B. Derivation of the primitive quotient K_3
  C. Derivation of p=N+1
  D. Enumeration derivation of (G1,G2,G3)=(24,64,80)
  E. Incidence derivation of seam weights {2,10,30}
  F. Structural derivation of B=137, delta1, capacity C2
  G. Fixed-point/live-boundary response for 1/alpha
  H. Graph-QED / discrete Maxwell bridge
  I. SU(3) appendix as consistency check
  J. Mass hook kept separate from alpha

Honest boundary
---------------
This is not a full derivation of continuum QED or the Standard Model.
It is a first-principles combinatorial/algebraic origin candidate for 1/alpha,
with a discrete U(1)/Maxwell bridge showing how the same primitive current
supports electromagnetic-like gauge dynamics.

The experimental value of 1/alpha appears only at final comparison.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, product, permutations
import math
from typing import Dict, List, Tuple

import numpy as np


# =============================================================================
# UTILS
# =============================================================================

def banner(title: str) -> None:
    print("\n" + "=" * 110)
    print(f"  {title}")
    print("=" * 110)


def subbanner(title: str) -> None:
    print("\n" + "-" * 110)
    print(f"  {title}")
    print("-" * 110)


def approx_eq(a: float, b: float, tol: float = 1e-12) -> bool:
    return abs(a - b) <= tol


@dataclass(frozen=True)
class CoreConstants:
    N: int
    p: int
    Q: float
    G1: int
    G2: int
    G3: int
    w12: int
    w13: int
    w23: int
    w_total: int
    DIM: int
    N_S: int
    S_E: int
    denom: int
    B: int
    delta1: float
    C2_capacity: int
    alpha_static: float
    alpha_unloaded_capacity: float
    alpha_fixed_point: float


# =============================================================================
# SECTION 0 — FIRST-PRINCIPLES LEDGER
# =============================================================================

def section_0_first_principles_ledger() -> None:
    banner("SECTION 0 — FIRST-PRINCIPLES LEDGER")

    print("""
This script starts from a deliberately small primitive ledger:

  P1. Distinction
      There is at least one difference: A ≠ B.
      Without distinction there is no relation, no boundary, no current.

  P2. Boundary
      A localized distinction creates an inside/outside separation.
      In chain-complex language, a physical boundary has no boundary of its own:
          ∂² = 0.
      Therefore primitive flow cannot terminate at loose endpoints.

  P3. Pairwise locality
      The first relation is adjacency between two patches.
      Higher relations must be built from pairwise relations.

  P4. Restorative isotropy
      At the primitive level no patch pair is privileged.
      If a relation is allowed between one pair, it is allowed between all pairs.
      This forces complete adjacency at the primitive quotient stage.

  P5. Single primitive closed current
      The first non-trivial current has exactly one independent loop:
          β1 = 1.
      β1 = 0 gives no closed current.
      β1 > 1 gives extra unforced primitive currents.

  P6. Minimal internal/external closure
      N internal patches require one exterior/reference state.
      This gives p = N + 1.
      More exterior states add unforced labels.

  P7. No target-loading
      Experimental 1/alpha is not used to choose N, p, G-values, weights,
      leakage, or the fixed-point equation.

  P8. No-new-invariant rule
      A correction can enter the main prediction only if it is generated by
      existing derived structure. Otherwise it goes into the guardrail ledger.
""")



# =============================================================================
# SECTION 0B — WHY THESE PRINCIPLES?
# =============================================================================

def section_0b_why_these_principles() -> None:
    banner("SECTION 0B — WHY THESE PRINCIPLES?")

    print("""
Important honesty upgrade:

The primitive principles P1-P8 are NOT claimed to be proven from deeper known
physics. They are the minimal design rules for a closed algebraic system with
no loose endpoints, no external selection rule, and exactly one primitive
closed current.

This matters because P4 and P5 do real work.

A critic could ask:
    Why K_3 rather than C_3?
    Why a complete graph rather than a selected non-complete graph?
    Why exactly one primitive current rather than many?
    Why not a multigraph with weighted edges inserted by hand?

The answer is:

  1. Completeness avoids an external selection rule.
     If the primitive system is isotropic, no patch pair may be privileged.
     A missing seam says "this pair is not coupled" while another pair is.
     That requires extra information not contained in distinction + boundary.

  2. Completeness minimizes hidden bookkeeping.
     A non-complete graph needs a rule specifying which pairs are allowed.
     A multigraph needs a rule specifying edge multiplicities.
     Both add structure before the first current exists.

  3. β1=1 prevents degenerate primitive closure.
     β1=0 gives no closed current.
     β1>1 gives multiple inequivalent primitive currents and therefore a
     choice of which current is first. That is another hidden selection rule.

  4. Planarity keeps the primitive quotient embeddable on the S² boundary
     without crossings or singular seam choices.

So the claim is not:
    "These principles are mathematically inevitable from all possible logic."

The claim is:
    "If we impose the minimal closed-current rules — no loose endpoints,
     complete primitive adjacency, S² embeddability, and exactly one loop —
     then the rest is forced."

This is the defensible posture:
    a self-contained closed system whose downstream integers and response
    structure are determined once the primitive constraints are accepted.

Physics interpretation:
    We do not yet prove nature must obey these constraints.
    We test whether these constraints generate the right structures:
        K_3,
        one closed current,
        U(1)-like phase transport,
        discrete Maxwell structure,
        the 137 base,
        the alpha fixed point,
        and the separated mass hook.
""")


# =============================================================================
# SECTION 1 — BOUNDARY NILPOTENCY AND CLOSED CURRENT
# =============================================================================

def oriented_incidence(n_vertices: int, edges: List[Tuple[int, int]]) -> np.ndarray:
    D = np.zeros((n_vertices, len(edges)))
    for e, (a, b) in enumerate(edges):
        D[a, e] = -1.0
        D[b, e] = +1.0
    return D


def section_1_boundary_nilpotency() -> None:
    banner("SECTION 1 — BOUNDARY NILPOTENCY: WHY CURRENTS MUST CLOSE")

    print("""
A primitive boundary is represented by a chain complex.

For a triangle face:
    face boundary = e01 + e12 + e20.

The boundary of that boundary must vanish:
    ∂(∂face) = 0.

This is the algebraic version of "no loose endpoints".
""")

    edges = [(0, 1), (1, 2), (2, 0)]
    D = oriented_incidence(3, edges)
    face_boundary = np.array([1.0, 1.0, 1.0])
    boundary_of_boundary = D @ face_boundary

    print("Oriented edges:", edges)
    print("Incidence matrix ∂1 = D:")
    print(D)
    print("Face boundary vector ∂2(face) =", face_boundary)
    print("∂1 ∂2(face) = D @ face_boundary =", boundary_of_boundary)

    assert np.allclose(boundary_of_boundary, 0), "Boundary of boundary must vanish."

    print("""
✓ The primitive loop current is forced to be divergence-free.
This is the root of the later U(1)/Maxwell bridge.
""")


# =============================================================================
# SECTION 2 — DERIVE K_3, NOT ASSUME IT
# =============================================================================

def beta1_for_graph(n_vertices: int, edges: List[Tuple[int, int]]) -> int:
    """For connected graphs only: β1 = E - V + 1."""
    return len(edges) - n_vertices + 1


def complete_graph_edges(N: int) -> List[Tuple[int, int]]:
    return list(combinations(range(N), 2))


def complete_graph_planar(N: int) -> bool:
    """K_N is planar iff N <= 4."""
    return N <= 4


def beta1_complete_graph(N: int) -> int:
    return N * (N - 1) // 2 - N + 1


def section_2_derive_k3() -> int:
    banner("SECTION 2 — DERIVING THE PRIMITIVE QUOTIENT K_3")

    print("""
From P4, primitive restorative isotropy says the first quotient is complete:
    G = K_N.

Why complete?
    If patch i can restore against patch j, then by isotropy every pair must
    have the same allowed direct relation. A missing edge would pick a preferred
    non-relation and break primitive isotropy.

Now impose:

  1. Complete adjacency:     G = K_N.
  2. Planar boundary quotient: K_N planar.
  3. Single primitive current: β1(K_N)=1.

For K_N:
    E = N(N-1)/2
    β1 = E - V + 1
       = N(N-1)/2 - N + 1
       = (N-1)(N-2)/2.

Set β1=1:
    (N-1)(N-2)/2 = 1
    (N-1)(N-2) = 2
    N = 3.

So the primitive quotient is K_3.
""")

    print(f"{'N':>3} {'edges':>6} {'K_N planar':>12} {'β1(K_N)':>10} {'β1=1':>8} {'survives':>10}")
    survivors = []
    for N in range(1, 9):
        E = N * (N - 1) // 2
        planar = complete_graph_planar(N)
        beta1 = beta1_complete_graph(N)
        one_loop = beta1 == 1
        survives = planar and one_loop
        if survives:
            survivors.append(N)
        print(f"{N:>3} {E:>6} {str(planar):>12} {beta1:>10} {str(one_loop):>8} {str(survives):>10}")

    assert survivors == [3], f"Only N=3 should survive; got {survivors}"

    print("""
Relaxation audit:
  If completeness is removed, larger simple cycles C4, C5, ... also have β1=1.
  They are rejected because they contain missing pairwise restorative relations.
  This is why K_3 is not just selected by β1; it is selected by:
      completeness + planarity + β1=1.
""")

    N = 3
    print("✓ Derived N = 3 and primitive quotient K_3.")
    return N


# =============================================================================
# SECTION 3 — DERIVE p = N + 1
# =============================================================================

def section_3_derive_p(N: int) -> Tuple[int, float]:
    banner("SECTION 3 — DERIVING p = N + 1")

    print("""
The quotient has N internal patch labels.

But a boundary distinction is not complete with internal labels alone:
    it also needs an exterior/reference state.

Minimal closure:
    p = N internal states + 1 exterior/reference state = N + 1.

Audit:
    p = N       : internal states only, no explicit outside/reference channel.
    p = N + 1   : minimal internal/external distinction.
    p > N + 1   : extra exterior labels with no primitive source.

Thus:
    p = N + 1.
For N=3:
    p = 4.
Then:
    Q = 1/p = 1/4.

Q is the primitive one-out-of-four leakage/coarse-graining fraction.
""")

    candidates = [
        (N, "reject: no explicit exterior/reference state"),
        (N + 1, "accept: minimal internal/external closure"),
        (N + 2, "reject: adds an unforced extra exterior label"),
    ]

    for p_candidate, verdict in candidates:
        print(f"p = {p_candidate:<3} -> {verdict}")

    p = N + 1
    Q = 1.0 / p

    assert p == 4
    assert approx_eq(Q, 0.25)

    print(f"\n✓ Derived p = {p}, Q = {Q}.")
    return p, Q


# =============================================================================
# SECTION 4 — DERIVE COUNT BASIS (24,64,80)
# =============================================================================

def active_seam_count(config: Tuple[int, int, int], seams: List[Tuple[int, int]]) -> int:
    return sum(1 for a, b in seams if config[a] != config[b])


def section_4_count_basis(N: int, p: int) -> Tuple[int, int, int, Dict[int, int]]:
    banner("SECTION 4 — DERIVING COUNT BASIS (G1,G2,G3) = (24,64,80)")

    print("""
We now count configurations directly from K_3 and p=4.

A configuration is:
    c = (c0,c1,c2), each ci ∈ {0,1,2,3}.

A seam is active if its endpoint states are distinct.

There are three seams:
    (0,1), (0,2), (1,2).

Derived counts:

  G1 — fully active count
      All three patches have distinct states:
          G1 = p(p-1)(p-2)
             = 4*3*2
             = 24.

  G2 — total configuration volume
          G2 = p^N
             = 4^3
             = 64.

  G3 — excess closed-current transport
      Sum active seams over all configurations, then subtract one equilibrium
      channel per configuration:
          total seam activity = number_of_seams * p^(N-1) * (p-1)
                              = 3 * 4^2 * 3
                              = 144.
          G3 = total_activity - G2
             = 144 - 64
             = 80.

This section brute-forces the same counts as a reproducibility check.
""")

    seams = [(0, 1), (0, 2), (1, 2)]
    configs = list(product(range(p), repeat=N))
    active_counts = [active_seam_count(c, seams) for c in configs]

    histogram: Dict[int, int] = {}
    for a in active_counts:
        histogram[a] = histogram.get(a, 0) + 1

    G1_brute = sum(1 for a in active_counts if a == 3)
    G2_brute = len(configs)
    total_activity_brute = sum(active_counts)
    G3_brute = total_activity_brute - G2_brute

    G1_closed = p * (p - 1) * (p - 2)
    G2_closed = p ** N
    n_seams = N * (N - 1) // 2
    total_activity_closed = n_seams * (p ** (N - 1)) * (p - 1)
    G3_closed = total_activity_closed - G2_closed

    print("Active seam histogram:", dict(sorted(histogram.items())))
    print(f"G1 brute = {G1_brute}, closed = {G1_closed}")
    print(f"G2 brute = {G2_brute}, closed = {G2_closed}")
    print(f"total activity brute = {total_activity_brute}, closed = {total_activity_closed}")
    print(f"G3 brute = {G3_brute}, closed = {G3_closed}")

    assert G1_brute == G1_closed == 24
    assert G2_brute == G2_closed == 64
    assert G3_brute == G3_closed == 80

    print("""
✓ Count basis derived from K_3 and p=4:
    G1 = 24
    G2 = 64
    G3 = 80
""")

    return G1_closed, G2_closed, G3_closed, histogram


# =============================================================================
# SECTION 5 — DERIVE SEAM WEIGHTS {2,10,30}
# =============================================================================

def solve_seam_weights(G1: int, G2: int, G3: int) -> Tuple[int, int, int, int]:
    I = np.array([
        [1, 1, 0],
        [1, 0, 1],
        [0, 1, 1],
    ], dtype=float)
    B_vec = np.array([G1, G2, G3], dtype=float)
    w = np.linalg.solve(2 * I, B_vec)
    rounded = tuple(int(round(x)) for x in w)
    assert np.allclose(w, rounded), f"Non-integer seam weights: {w}"
    return rounded[0], rounded[1], rounded[2], sum(rounded)


def section_5_seam_weights(G1: int, G2: int, G3: int) -> Tuple[int, int, int, int]:
    banner("SECTION 5 — DERIVING SEAM WEIGHTS FROM B = 2 I w")

    print("""
Let:
    B = (G1, G2, G3)^T = (24,64,80)^T.

Each patch touches two seams. Let:
    w = (w12,w13,w23)^T.

Patch-seam incidence matrix:
    I = [[1,1,0],
         [1,0,1],
         [0,1,1]]

Restorative bidirectional load gives:
    B = 2 I w.

Solving this linear system gives the seam weights.
""")

    I = np.array([
        [1, 1, 0],
        [1, 0, 1],
        [0, 1, 1],
    ], dtype=float)
    B_vec = np.array([G1, G2, G3], dtype=float)

    print("I =")
    print(I)
    print("B =", B_vec.astype(int))

    w12, w13, w23, w_total = solve_seam_weights(G1, G2, G3)

    print(f"w12 = {w12}")
    print(f"w13 = {w13}")
    print(f"w23 = {w23}")
    print(f"w_total = {w_total}")

    # Relabel audit.
    target = sorted([w12, w13, w23])
    relabel_ok = True
    for perm in permutations([G1, G2, G3]):
        wp = np.linalg.solve(2 * I, np.array(perm, dtype=float))
        if sorted(int(round(x)) for x in wp) != target:
            relabel_ok = False
            break

    print("Relabel audit:", relabel_ok)

    assert (w12, w13, w23) == (2, 10, 30)
    assert w_total == 42
    assert relabel_ok

    print("✓ Seam weights derived: {2,10,30}.")
    return w12, w13, w23, w_total


# =============================================================================
# SECTION 6 — DERIVE STRUCTURAL CONSTANTS
# =============================================================================

def section_6_structural_constants(
    N: int,
    p: int,
    Q: float,
    G1: int,
    G2: int,
    G3: int,
    w_total: int,
) -> Tuple[int, int, int, int, int, float, int, float, float, float]:
    banner("SECTION 6 — DERIVING STRUCTURAL CONSTANTS")

    print("""
Every object below is derived from the already-built structure.

  DIM = N² + 2
      N² directed relational slots of the patch matrix
      + 2 boundary polarity markers: inside/outside.

      For N=3:
          DIM = 9 + 2 = 11.

  N_S = (G2 - G1)/8
      Inter-fold gap modes normalized by the 8-generator qutrit closure.
      For G2=64, G1=24:
          N_S = 40/8 = 5.

  S_E = 8*N_S
      Minimal instanton/action barrier in the old mass hook:
          S_E = 40.

  denom = G3 + N
      Full stress budget plus patch zero modes:
          denom = 80 + 3 = 83.

  B = w_total*N + DIM
      Base inverse coupling:
          B = 42*3 + 11 = 137.

  delta1 = Q/(N+p)
      First-order leakage:
          Q distributed across the N patch channels plus p fold-state channels:
          delta1 = (1/4)/(3+4) = 1/28.

  C2_capacity = G3*p*DIM
      Full second-order boundary-response capacity:
          G3 excess transport
          * p fold states
          * DIM relational dimension
          = 80*4*11 = 3520.
""")

    DIM = N ** 2 + 2
    N_S = (G2 - G1) // 8
    S_E = 8 * N_S
    denom = G3 + N
    B = w_total * N + DIM
    delta1 = Q / (N + p)
    C2_capacity = G3 * p * DIM

    alpha_static = B + delta1
    alpha_unloaded_capacity = B + delta1 + 1.0 / C2_capacity

    # Live fixed point:
    # A = B + delta1 + A/(B*C2)
    alpha_fixed_point = (B + delta1) / (1.0 - 1.0 / (B * C2_capacity))

    print(f"DIM = N²+2 = {DIM}")
    print(f"N_S = (G2-G1)/8 = {N_S}")
    print(f"S_E = 8*N_S = {S_E}")
    print(f"denom = G3+N = {denom}")
    print(f"B = w_total*N + DIM = {B}")
    print(f"delta1 = Q/(N+p) = {delta1:.15f}")
    print(f"C2_capacity = G3*p*DIM = {C2_capacity}")
    print(f"alpha_static = {alpha_static:.15f}")
    print(f"alpha_unloaded_capacity = {alpha_unloaded_capacity:.15f}")
    print(f"alpha_fixed_point = {alpha_fixed_point:.15f}")

    assert DIM == 11
    assert N_S == 5
    assert S_E == 40
    assert denom == 83
    assert B == 137
    assert approx_eq(delta1, 1.0 / 28.0)
    assert C2_capacity == 3520

    return (
        DIM,
        N_S,
        S_E,
        denom,
        B,
        delta1,
        C2_capacity,
        alpha_static,
        alpha_unloaded_capacity,
        alpha_fixed_point,
    )


# =============================================================================
# SECTION 7 — FIXED-POINT ALPHA DERIVATION
# =============================================================================

def section_7_alpha_fixed_point(constants: CoreConstants) -> None:
    banner("SECTION 7 — DERIVING THE LIVE FIXED-POINT ALPHA CANDIDATE")

    print("""
The earlier static version stopped at:
    A_static = B + delta1.

The upgraded version derives a live response instead of inserting a chosen
second-order number.

Define a boundary response variable x and action:

    S(x; A) = 1/2 C2 x² - (A/B) x.

Stationarity:
    ∂S/∂x = C2 x - A/B = 0
    x(A) = A/(B*C2).

Now impose self-consistency:
    A = B + delta1 + x(A)
      = B + delta1 + A/(B*C2).

Solve:
    A(1 - 1/(B*C2)) = B + delta1
    A = (B + delta1)/(1 - 1/(B*C2)).

This is the "holy grail" direction:
    derive f(A), then solve the fixed point,
    instead of choosing a correction after seeing the target.
""")

    B = constants.B
    delta1 = constants.delta1
    C2 = constants.C2_capacity
    A = constants.alpha_fixed_point

    coeff = 1.0 / (B * C2)
    x = A * coeff

    print(f"B = {B}")
    print(f"delta1 = {delta1:.15f}")
    print(f"C2 = {C2}")
    print(f"response coefficient 1/(B*C2) = {coeff:.15e}")
    print(f"live response x(A*) = {x:.15e}")
    print(f"A* = {A:.15f}")

    assert approx_eq(A, (B + delta1) / (1.0 - coeff))
    print("✓ Fixed point solved.")


# =============================================================================
# SECTION 8 — BLIND AUDITS AND HIGHER-ORDER GUARDRAIL
# =============================================================================

def section_8_blind_audits(constants: CoreConstants) -> None:
    banner("SECTION 8 — BLIND AUDITS: NO TARGET NEEDED")

    print("""
This audit does not compare to the experimental value.

It asks whether the terms are structurally generated:

  delta1:
      Q/(N+p) uses the primitive leakage Q spread over all patch/fold channels.

  C2:
      G3*p*DIM uses all available second-order capacity:
        excess transport * fold states * relational dimension.

  fixed response:
      A/(B*C2) comes from stationarity of the response action.

Alternatives can be listed, but they either miss part of the capacity, double
count Q, or introduce a new invariant.
""")

    N, p, Q = constants.N, constants.p, constants.Q
    G2, G3 = constants.G2, constants.G3
    DIM, B, C2 = constants.DIM, constants.B, constants.C2_capacity
    A = constants.alpha_fixed_point

    candidates = [
        ("Q/(N+p)", Q / (N + p), "accepted first-order leakage"),
        ("1/(G3*p*DIM)", 1 / (G3 * p * DIM), "unloaded full-capacity inverse"),
        ("A/(B*C2)", A / (B * C2), "accepted live response from stationarity"),
        ("Q/G2", Q / G2, "linear leakage again; not second-order"),
        ("1/G3", 1 / G3, "too large and misses p,DIM"),
        ("1/(G2*DIM)", 1 / (G2 * DIM), "misses excess transport G3 and p"),
        ("Q/(G3*p*DIM)", Q / (G3 * p * DIM), "double-counts Q in second order"),
        ("1/(B*C2)", 1 / (B * C2), "coefficient only, not additive by itself"),
    ]

    print(f"{'candidate':>20} {'value':>22}  comment")
    for name, value, comment in candidates:
        print(f"{name:>20} {value:>22.15e}  {comment}")

    print("""
Higher-order guardrail:
  The model does NOT prove all quartic/higher even terms vanish.
  It excludes them from the main prediction under the no-new-invariant rule
  until a derived C4 invariant exists.

Orientation symmetry:
  x -> -x reverses current orientation. Primitive scalar response keeps
  even powers. Odd terms require derived orientation-breaking structure.
""")

    x = A / (B * C2)
    C4_if_C2_squared = C2 ** 2
    quartic_scale = (x ** 3) * C4_if_C2_squared / C2

    print(f"live x = {x:.15e}")
    print(f"x² = {x*x:.15e}")
    print(f"C2*x² = {C2*x*x:.15e}")
    print(f"quartic scale if C4=C2² = {quartic_scale:.15e}")


# =============================================================================
# SECTION 9 — TARGET COMPARISON ONLY HERE
# =============================================================================

def section_9_target_comparison(constants: CoreConstants, alpha_target: float = 137.035999084) -> None:
    banner("SECTION 9 — TARGET COMPARISON: EXPERIMENT ENTERS HERE ONLY")

    print("""
The target value enters only now, after all model quantities are derived.
""")

    rows = [
        ("static B+δ1", constants.alpha_static),
        ("unloaded capacity", constants.alpha_unloaded_capacity),
        ("live fixed point", constants.alpha_fixed_point),
    ]

    print(f"Target 1/alpha = {alpha_target:.15f}")
    print(f"{'candidate':>22} {'prediction':>22} {'abs error':>18} {'relative error':>18}")
    for name, value in rows:
        err = value - alpha_target
        rel = err / alpha_target
        print(f"{name:>22} {value:>22.15f} {err:>18.9e} {rel:>18.9e}")

    static_err = abs(constants.alpha_static - alpha_target)
    fixed_err = abs(constants.alpha_fixed_point - alpha_target)
    print(f"\nError-collapse factor static -> fixed point: {static_err/fixed_err:.3f}x")


# =============================================================================
# SECTION 10 — DISCRETE MAXWELL / GRAPH-QED BRIDGE
# =============================================================================

def section_10_discrete_maxwell_bridge(constants: CoreConstants) -> None:
    banner("SECTION 10 — DISCRETE MAXWELL / GRAPH-QED BRIDGE")

    print("""
This section answers the "not QED" criticism honestly.

It does not claim full continuum QED.

The stronger and more accurate claim is:
    K_3 topology naturally hosts the algebraic structures that underlie
    U(1)-type gauge physics.

It shows that the same first-principles closed current on K_3 supports:

  - U(1) phase transport on edges,
  - curvature F=dA,
  - dF=0 from d²=0,
  - conserved source current D j = 0,
  - minimal coupling on graph fields,
  - one massless loop mode from β1=1.

This is the bridge from combinatorial origin candidate to gauge-compatible
field dynamics. It shows structural compatibility with electromagnetism
without pretending to be a complete continuum QED derivation.
""")

    vertices = [0, 1, 2]
    edges = [(0, 1), (1, 2), (2, 0)]
    D = oriented_incidence(len(vertices), edges)

    print("Incidence D:")
    print(D)

    j = np.array([1.0, 1.0, 1.0])
    print("primitive current j =", j)
    print("D @ j =", D @ j)
    assert np.allclose(D @ j, 0)

    # Discrete exterior derivatives.
    d0 = np.zeros((3, 3))
    for e, (a, b) in enumerate(edges):
        d0[e, a] = -1.0
        d0[e, b] = 1.0

    d1 = np.ones((1, 3))  # oriented loop 0->1->2->0

    print("\nd0 (0-forms -> 1-forms):")
    print(d0)
    print("d1 (1-forms -> loop flux):")
    print(d1)
    print("d1 @ d0 =")
    print(d1 @ d0)
    assert np.allclose(d1 @ d0, 0)

    # U(1) link variables and curvature.
    A = np.array([0.10, 0.20, -0.15])
    U = np.exp(1j * A)
    F = d1 @ A

    print("\nU(1) link variables:")
    print("A =", A)
    print("U=exp(iA) =", U)
    print("F=dA loop flux =", F[0])

    # Minimal coupling.
    psi = np.array([1.0 + 0j, 0.5 + 0.5j, 0.2 - 0.3j])
    Dpsi = np.zeros(3, dtype=complex)
    for e, (a, b) in enumerate(edges):
        Dpsi[e] = psi[b] - U[e] * psi[a]

    print("\nMatter field ψ =", psi)
    print("Gauge-covariant edge derivative D_Aψ =", Dpsi)

    A_small = np.array([0.01, 0.02, -0.015])
    ordinary = np.array([psi[b] - psi[a] for a, b in edges])
    interaction = -1j * A_small * np.array([psi[a] for a, b in edges])

    print("\nSmall-A split:")
    print("ordinary difference =", ordinary)
    print("interaction -iAψ_source =", interaction)

    # Cycle-space photon analogue.
    u, s, vh = np.linalg.svd(D)
    rank = int(np.sum(s > 1e-12))
    nullity = D.shape[1] - rank
    cycle = vh[-1]
    cycle = cycle / np.linalg.norm(cycle)

    print("\nCycle-space audit:")
    print("singular values =", s)
    print("rank(D) =", rank)
    print("nullity(D) =", nullity)
    print("cycle/null vector =", cycle)
    print("D @ cycle =", D @ cycle)

    assert nullity == 1
    assert np.allclose(D @ cycle, 0, atol=1e-12)

    print("""
✓ Discrete Maxwell bridge complete.

Best current interpretation:
    The primitive K_3 quotient does not merely fit numbers.
    It generates the correct kind of gauge skeleton:
        closed current -> U(1) phase -> curvature -> conservation ->
        covariant coupling -> one harmonic photon-like mode.

The continuum-QED step remains future work:
    many K_3 cells -> coarse-grained U(1) bundle -> continuum field theory.
""")


# =============================================================================
# SECTION 11 — SU(3) CONSISTENCY APPENDIX
# =============================================================================

def gell_mann_matrices() -> List[np.ndarray]:
    lam = [None] * 8
    lam[0] = np.array([[0,1,0],[1,0,0],[0,0,0]], dtype=complex)
    lam[1] = np.array([[0,-1j,0],[1j,0,0],[0,0,0]], dtype=complex)
    lam[2] = np.array([[1,0,0],[0,-1,0],[0,0,0]], dtype=complex)
    lam[3] = np.array([[0,0,1],[0,0,0],[1,0,0]], dtype=complex)
    lam[4] = np.array([[0,0,-1j],[0,0,0],[1j,0,0]], dtype=complex)
    lam[5] = np.array([[0,0,0],[0,0,1],[0,1,0]], dtype=complex)
    lam[6] = np.array([[0,0,0],[0,0,-1j],[0,1j,0]], dtype=complex)
    lam[7] = np.array([[1,0,0],[0,1,0],[0,0,-2]], dtype=complex) / np.sqrt(3)
    return lam


def stress_invariant(generators: List[np.ndarray]) -> float:
    total = 0.0
    for i in range(len(generators)):
        for j in range(i + 1, len(generators)):
            comm = generators[i] @ generators[j] - generators[j] @ generators[i]
            total += float(np.real(np.trace(comm.conj().T @ comm)))
    return total


def section_11_su3_appendix(constants: CoreConstants) -> None:
    banner("SECTION 11 — SU(3) CONSISTENCY APPENDIX")

    print("""
The main alpha derivation uses the K_3 combinatorial chain.
This appendix verifies that the same (24,64,80) pattern is mirrored in
the SU(3)/qutrit seam algebra.
""")

    lam = gell_mann_matrices()

    Gamma1 = stress_invariant([lam[0], lam[1], lam[2]])

    fold2_direct = [lam[0], lam[1], lam[2], lam[5], lam[6], lam[7]]
    Gamma2_direct = stress_invariant(fold2_direct)
    comm_composite = lam[3] @ lam[4] - lam[4] @ lam[3]
    composite_self = float(np.real(np.trace(comm_composite.conj().T @ comm_composite)))
    Gamma2 = Gamma2_direct + composite_self

    fold3_all = [lam[i] for i in range(8)]
    Gamma3_raw = stress_invariant(fold3_all)
    closure = 0.0
    for cg in [lam[3], lam[4]]:
        for eg in [lam[0], lam[1], lam[5], lam[6]]:
            comm = cg @ eg - eg @ cg
            closure += float(np.real(np.trace(comm.conj().T @ comm)))
    Gamma3 = Gamma3_raw - closure

    X12 = lam[0]
    X23 = lam[5]
    X13 = lam[3]
    composite_match = np.allclose(X12 @ X23 + X23 @ X12, X13)

    print(f"Γ1² = {Gamma1:.0f}")
    print(f"Γ2² = {Gamma2_direct:.0f} + {composite_self:.0f} = {Gamma2:.0f}")
    print(f"Γ3² = {Gamma3_raw:.0f} - {closure:.0f} = {Gamma3:.0f}")
    print("Composite seam identity {X12,X23}=X13:", composite_match)

    assert int(round(Gamma1)) == constants.G1
    assert int(round(Gamma2)) == constants.G2
    assert int(round(Gamma3)) == constants.G3
    assert composite_match

    print("✓ SU(3) consistency check passes.")


# =============================================================================
# SECTION 12 — MASS HOOK KEPT SEPARATE
# =============================================================================

def section_12_mass_hook(constants: CoreConstants) -> None:
    banner("SECTION 12 — MASS HOOK, SEPARATE FROM ALPHA")

    print("""
This preserves the old mass-scale work without letting it contaminate alpha.

The alpha derivation does not use particle masses.

The mass hook uses one physical anchor:
    M_Pl.

Then:
    C = M_Pl exp(-S_E)/(denom*pi).
""")

    M_Pl_GeV = 1.220890e19
    M_Pl_MeV = M_Pl_GeV * 1e3

    C = M_Pl_MeV * math.exp(-constants.S_E) / (constants.denom * math.pi)

    S2 = 17 / 64
    S1 = 1 / 8
    Ze = 1 / (constants.N * constants.N_S)
    heavy = 1 + 1 / (constants.G3 + constants.G2)

    m_tau = C * math.sqrt(constants.G3)
    m_mu = C * math.sqrt(constants.G2) * constants.Q * S2
    m_e = C * math.sqrt(constants.G1) * constants.Q**2 * S1 * Ze * heavy

    targets = {
        "tau": 1776.86,
        "muon": 105.6584,
        "electron": 0.51100,
    }

    print(f"C = {C:.8f} MeV")
    print(f"{'quantity':>12} {'prediction MeV':>18} {'diagnostic target':>20} {'error %':>12}")
    for name, pred in [("tau", m_tau), ("muon", m_mu), ("electron", m_e)]:
        err = (pred / targets[name] - 1) * 100
        print(f"{name:>12} {pred:>18.8f} {targets[name]:>20.8f} {err:>12.6f}")


# =============================================================================
# SECTION 13 — CRITICISM LEDGER
# =============================================================================

def section_13_criticism_ledger() -> None:
    banner("SECTION 13 — CRITICISM LEDGER")

    rows = [
        (
            "K_3 was assumed.",
            "Fixed: K_3 is derived from complete adjacency + planarity + β1=1.",
        ),
        (
            "p=4 was assumed.",
            "Fixed: p=N+1 is derived from minimal internal/external closure.",
        ),
        (
            "G-values were arbitrary.",
            "Fixed: (24,64,80) are derived by enumeration and closed-form counting.",
        ),
        (
            "Weights were selected.",
            "Fixed: {2,10,30} solve B=2Iw uniquely, with relabel audit.",
        ),
        (
            "Residual was fitted.",
            "Improved: δ1=Q/(N+p); live response follows from stationary action.",
        ),
        (
            "Second-order term not unique.",
            "Improved: static term is demoted; main result uses fixed-point response. Higher terms guarded.",
        ),
        (
            "This is not QED.",
            "Accepted. Section 10 is a discrete graph-QED bridge, not full continuum QED.",
        ),
        (
            "The primitive principles are design choices.",
            "Accepted and now explicit in Section 0B. The claim is conditional forcing, not proof from all deeper physics.",
        ),
        (
            "Why completeness instead of C3 or a selected sparse graph?",
            "Fixed in Section 0B/2: sparse graphs require an extra rule selecting missing seams; completeness is the no-selection primitive.",
        ),
        (
            "Masses are smuggled into alpha.",
            "Fixed: mass hook is separate; alpha uses no masses.",
        ),
    ]

    for issue, answer in rows:
        print(f"\nIssue:  {issue}\nAnswer: {answer}")


# =============================================================================
# SECTION 14 — DEPENDENCY TREE
# =============================================================================

def section_14_dependency_tree(constants: CoreConstants) -> None:
    banner("SECTION 14 — DEPENDENCY TREE")

    print(f"""
LEVEL 0:
  Distinction, boundary nilpotency, locality, restorative isotropy,
  single primitive current, minimal internal/external closure.

LEVEL 0B:
  These are explicit minimal-design constraints, not claimed as proven
  necessities from deeper known physics. Completeness is used because any
  sparse primitive graph needs an extra seam-selection rule.

LEVEL 1:
  Complete graph K_N + planarity + β1=1 -> N={constants.N}.

LEVEL 2:
  p=N+1={constants.p}; Q=1/p={constants.Q}.

LEVEL 3:
  K_3 configurations over p states ->
  (G1,G2,G3)=({constants.G1},{constants.G2},{constants.G3}).

LEVEL 4:
  B_vec=(G1,G2,G3); B_vec=2Iw ->
  seam weights ({constants.w12},{constants.w13},{constants.w23}),
  w_total={constants.w_total}.

LEVEL 5:
  DIM=N²+2={constants.DIM};
  B=w_total*N+DIM={constants.B};
  δ1=Q/(N+p)={constants.delta1:.15f}.

LEVEL 6:
  C2=G3*p*DIM={constants.C2_capacity};
  stationary response x(A)=A/(B*C2);
  fixed point A=(B+δ1)/(1-1/(B*C2))
  = {constants.alpha_fixed_point:.15f}.

LEVEL 7:
  Discrete Maxwell bridge, SU(3) consistency appendix, separated mass hook.
""")


# =============================================================================
# BUILD CONSTANTS AND RUN
# =============================================================================

def build_constants() -> CoreConstants:
    section_0_first_principles_ledger()
    section_0b_why_these_principles()
    section_1_boundary_nilpotency()
    N = section_2_derive_k3()
    p, Q = section_3_derive_p(N)
    G1, G2, G3, _hist = section_4_count_basis(N, p)
    w12, w13, w23, w_total = section_5_seam_weights(G1, G2, G3)
    (
        DIM,
        N_S,
        S_E,
        denom,
        B,
        delta1,
        C2_capacity,
        alpha_static,
        alpha_unloaded_capacity,
        alpha_fixed_point,
    ) = section_6_structural_constants(N, p, Q, G1, G2, G3, w_total)

    return CoreConstants(
        N=N,
        p=p,
        Q=Q,
        G1=G1,
        G2=G2,
        G3=G3,
        w12=w12,
        w13=w13,
        w23=w23,
        w_total=w_total,
        DIM=DIM,
        N_S=N_S,
        S_E=S_E,
        denom=denom,
        B=B,
        delta1=delta1,
        C2_capacity=C2_capacity,
        alpha_static=alpha_static,
        alpha_unloaded_capacity=alpha_unloaded_capacity,
        alpha_fixed_point=alpha_fixed_point,
    )


def run_book(alpha_target: float = 137.035999084) -> CoreConstants:
    banner("FORD MODEL — FIRST-PRINCIPLES MASTER SCRIPTBOOK RUN")
    constants = build_constants()

    section_7_alpha_fixed_point(constants)
    section_8_blind_audits(constants)
    section_9_target_comparison(constants, alpha_target=alpha_target)
    section_10_discrete_maxwell_bridge(constants)
    section_11_su3_appendix(constants)
    section_12_mass_hook(constants)
    section_13_criticism_ledger()
    section_14_dependency_tree(constants)

    banner("FINAL SUMMARY")
    print(f"""
First-principles derived chain:
  N={constants.N}
  p={constants.p}
  Q={constants.Q}
  G-values=({constants.G1},{constants.G2},{constants.G3})
  seam weights=({constants.w12},{constants.w13},{constants.w23})
  w_total={constants.w_total}
  DIM={constants.DIM}
  B={constants.B}
  δ1={constants.delta1:.15f}
  C2={constants.C2_capacity}

Alpha candidates:
  static B+δ1              = {constants.alpha_static:.15f}
  unloaded capacity        = {constants.alpha_unloaded_capacity:.15f}
  live fixed-point A*      = {constants.alpha_fixed_point:.15f}

Boundary:
  This is a first-principles combinatorial/algebraic origin candidate with
  a discrete U(1)/Maxwell bridge. It is not yet a full continuum QED derivation.

  The primitive principles are now stated honestly as minimal closure rules:
  once accepted, they force the downstream K_3 structure; they are not
  presented as proven necessities from deeper known physics.
""")

    return constants


if __name__ == "__main__":
    run_book()
